### ISSUE TITLE
scan delta does not work inside GDA - it looks delta is not a scannable in GDA context

### ISSUE THREAD

**Issue by fajinyuan** [DiamondLightSource/diffcalc#37]
>>> scan delta 40 90 10 hkl ct 1
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/scratch/gda_versions/gda_master2/workspace_git/gda-core.git/uk.ac.gda.core/scripts/gdascripts/scan/concurrentScanWrapper.py", line 114, in __call__
    argStruct = self.parseArgsIntoArgStruct(args)
  File "/scratch/gda_versions/gda_master2/workspace_git/gda-core.git/uk.ac.gda.core/scripts/gdascripts/scan/concurrentScanWrapper.py", line 198, in parseArgsIntoArgStruct
    raise Exception("First argument to scan command must be a scannable")
Exception: First argument to scan command must be a scannable
>>> delta
_fourc.delta : 66.4999418286

**Comment by fajinyuan** [comment]
It looks the diffcalc package defines its own 'Scannable' which is not GDA scannable

**Comment by fajinyuan** [comment]
GDA 'pos' and 'scan' command does not work with diffcalc's scannable - delta, eta, chi, phi>>> pos delta 66
```
Traceback (most recent call last):
  File '<input>', line 1, in <module>

java.lang.NullPointerException: null
>>> pos chi 1
Traceback (most recent call last):
  File '<input>', line 1, in <module>

java.lang.NullPointerException: null
>>> pos phi 1
Traceback (most recent call last):
  File '<input>', line 1, in <module>

java.lang.NullPointerException: null
>>> pos eta 1
Traceback (most recent call last):
  File '<input>', line 1, in <module>

java.lang.NullPointerException: null
```

**Comment by fajinyuan** [comment]
How ever reading values are working:
`>>> pos delta
_fourc.delta : 66.4999418286
>>> pos chi
_fourc.chi : 65.772254682
>>> pos phi
_fourc.phi : 90.0
>>> pos eta
_fourc.eta : 33.2499709143`

**Comment by fajinyuan** [comment]
I can confirm diffcalc's scannable here are not recognised as GDA Scannable.

**Comment by xen-0** [comment]
Strange - pretty sure the objects diffcalc creates on I16 are GDA scannables.
Diffcalc definitely *knows* about GDA scannables.

**Comment by fajinyuan** [comment]
Yes that's in the past. diffcalc on Master now have a script scannable.py in which there is a class 

```
class Scannable(object):
       pass
```
which everything else inherit from, not GDA's Scannable.

I think I have fixed this now but still need to test more before I can push to repo.
I also need to test diffcalc in IPython so I am not screw that up.

**Comment by fajinyuan** [comment]
Fixed and tested in GDA simulation
