### ISSUE TITLE
Provide command to select reflections used for U matrix calculation

### ISSUE THREAD

**Issue by robwalton** [DiamondLightSource/diffcalc#5]
Currently the first two are always used, meaning users reorder reflections in a way that they end up loosing track of which is which.

**Comment by isikhar** [comment]
``calcub`` and ``orientub`` commands can now accept indices or tags referencing stored reflections to use for UB matrix calculation. Fixed in 33b7f1d247f3834aea345c426b70d2fc9f5d60e3
